Feature base path
linuxserver/docker-netbox pull request #8
Opened 2021-01-02 21:14 UTC by xanmanning

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

closes #7 

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-netbox/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Adds `BASE_PATH` to the list of environment variables accepted which will populate the variable in configuration.py

## Benefits of this PR and context:

Container can be run behind a reverse proxy with a path, eg. https://yourdomain.com/netbox

## How Has This Been Tested?

 1. Built container
 2. Checked the contents of configuration.py

## Source / References:

 - https://netbox.readthedocs.io/en/stable/configuration/optional-settings

2021-01-02 21:22 UTC, tobbenb requested changes
Could you move the changelog entry to the top so it's the same as all other README's?

2021-01-02 23:05 UTC, xanmanning commented
@tobbenb is that better?

2021-01-31 19:56 UTC, xanmanning commented
Hi. Any updates?

2021-02-02 08:02 UTC, tobbenb approved these changes

2021-02-02 08:06 UTC, merged